apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:khKLtsuRLYfXAj6IUNMC0Y9b3EYLXPTmZUCV10Nu5KE=,iv:YqZkNtBaF6BffyMpAQADVQogI8qhwind7mW1fMWqgq4=,tag:t+/9Y4EFUteRPfdtmaSz4Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1czpgr946k9suyc5hjnf6t5r034rsemauh87dgddkm9adn5qx4crqlln5nd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6V1NtWXFZTmJ5bndoZ2F4
        bVVZUE9QZmV3OGJOZk54UTVMOHlKeWZubGw4CnIwZnBkYmxxcC9tRFZ3Q0tMM1pn
        T1RsMWdScTVNdDFZT2VKcHJ2WmpGM00KLS0tIHNSaXVzTVNwcmhkMHJNaTBzQ3JI
        djd0WXBKeE9rQWQrdFJJY1RGVENFM0kKyHQymPkh2Cvq8Rq/Hn13CtYnf3F41i1e
        /urz1flAHBIq8Ekpi5LcqrKQe2jC2V76+Hs8W66+jt4IqjjY99qVAg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-08T21:30:49Z"
  mac: ENC[AES256_GCM,data:C4OJXgiK1Xzn6XYm+vyjQWV8E/sU6rH7cT0yTeyhhU8G4rcMuwq1yBIpOAB6dVMkkAxH97sH1/hx/uky72HBsPngzDZ8xLgzrf4TxWosFd3W2/spgh5iJIRzmtZjb2RHWmNgIWUyc8OlzQ0B1/h9fOUUOxDkWDJL645DmQBTZ6E=,iv:4wHLVBCa/2Nyd7YZf/HrnwMkd2i+r1EiCkswi2nhaFc=,tag:NAgQYu7RN1CRNpItNfFnGA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
