apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:tbUgJG0qM99gSab6Wui9Ffvf0fEli3384Np8lrLL+7Of/RBFAyuQgg==,iv:RrklyjU/rE8Pjt5R0KN9U0V9Vay/0Iw8JLTjPwtbqTg=,tag:eTsJOX2HG2lvg7XQrYhmPg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1czpgr946k9suyc5hjnf6t5r034rsemauh87dgddkm9adn5qx4crqlln5nd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvV3lIOFByeDY4cHFCOHNU
        dWhVQlpJVFJQNmRxbkNJWEdUUkhmUU5KblhvCms1cVZ5OTE4N01xN2I3aUpHcEl3
        RXNvV3NYdEZ0N3R1dElLTUtKN3Y0a00KLS0tIExCMUJ6dGs3MGdZc2tRbk1BdmJm
        RVhzZmpTRkdJaUtuNUhaekVZOEphQ28KDu+9zzznjHMzUrpfkEMY99WwzcCAadZb
        zMW/uABw4KXANtlGX1x9+k0fjncT9MOv8cagyAHaX2/mJqM+7hbB+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-09T02:23:39Z"
  mac: ENC[AES256_GCM,data:wjTc4hflViKMfNWy2T4AzGQTS6S91rHvAr8oxosrw4x85pXGeJJA4Zs/wChqKIFo++m94wLBSJZrVbPNOFEYrNykK1Y+oLRZ9McEezG3kL44tM+YzcvENmUIFrl2iwUaAllX39XlmI5TMVO6iy8P4S/NyGc61SFDwxTTt0Pm62c=,iv:vA0gQWKgZabLizQAnmhjCSOWV+zdzSjPDHUBakGnwko=,tag:qsUPpQIjBoG+BgxiRoGTUg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
