apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:J0CMx/yrgRf41ix+,iv:s625EMOE5ute9qd5qakBm1sH/ZViTR0zpgEBlwoXThE=,tag:G0oct77S0jl+4LGWcBGe2g==,type:str]
  SECRET_ACME_EMAIL: ENC[AES256_GCM,data:+0rO2/QQ8OCbjWJbDnbEY9W2azUeeA==,iv:O5YJPr7+Aygpx8otlJDKgZt4rG+JVQLxGiKQROYcMec=,tag:UGuEha+RDU/n8PpaCcSyHg==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:+FzNN4P+2v6nBBO2MmoNqeE/ph9z2UBr0XKvQaQOik9fyvUx,iv:mBs1WewgetbA4k5puIPaEfNpwXsTcX7YfmAcuBBbJAI=,tag:dFYoKvs9pINoAm3xOZj/ww==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1czpgr946k9suyc5hjnf6t5r034rsemauh87dgddkm9adn5qx4crqlln5nd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJcHllS1RZNWhsYlBHUkVt
        SnJPbU1uQlY2c0JIMDZmMnkrbi8yaU0rRjJvCjlKcmlKM1RJUVcrYTF6TVpUZDd4
        ZlJDWGRkNXhkNU10MmpJalVqZ2poY0EKLS0tIFQ5d1BvVWlhQk9RVndURHRna1lz
        dlFZMHc4N0VNbjlFR2F0Ny9kanFPTTAKr6860fX9ZatVmVL5pens9w8Lnbe+Y8xK
        QNMs75IM3El8d4GXLQ8zI8Siz0aciqLh2/tHgWw5PNtZ6neN3jZv2w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-08T23:18:36Z"
  mac: ENC[AES256_GCM,data:wat6UqSVpTNVxJhJlF/oVWNl4lnpYmMUSHEbM0ebiGMTn1N1hr24KU3/BrMs4CbRXBaMgtnT9nSzMEsy+Qf7/lueedmqu3AYiSdonBaq8F3f9dhtGhB2IAo4pmNB8burYh1Y7tD7MWyCl4WYJRJBxmtjlT8uzoHlzwXyHWBqPH4=,iv:dyxh8XEQffP8diX6ZbPID1cuZCp2036jAl9bhbe/dsw=,tag:Xryxnw7oBV9s8B4O0nGong==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
