apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:yXkqlruogJOQ50UJoSERLlZcbSzMOYLySLd77voJeG1EiV22EOSFIw==,iv:NGZGKupbuUn1287RZJPA3Xoj6C2i3q+2nhHF3z+g0yU=,tag:BdVDcWR9SfGm6jH3IeoSrA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1czpgr946k9suyc5hjnf6t5r034rsemauh87dgddkm9adn5qx4crqlln5nd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5OXE4M2tHb001UGM2dWp3
        V1VrVllJbFhVS1lQT0RaMldZVVZwbWZCb1M4CmNhTktmNnZWR004eVpCNnVHT3E3
        Yld5VmM4aXhLN1VldExRVU9jaVQxb3MKLS0tIHpidkZpNzREVDFpaGxweE95aFFC
        SWNpdXBrdlg5SmxtMDlFVU5nb1llTWMKFw/VbogBNLHfUcN5lKvSLOY2xYM2loZD
        l7KY9YALZgkMZyZRDX6bWQY/GVISsLgBoqa6dTjjPbuE1RoMy7BNjg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-08T21:30:49Z"
  mac: ENC[AES256_GCM,data:pGPXJAAT/NIjn9aXUgnVbEwktLG6IwTzJqB/yMsHVJbvMpMbY/dv4k5mXOo/gMeK0FAgBB9eBIKLOEUplHz6vHXkYgaIV4IDcVtYI3wD/+vqV3x/9Hu2R3Q9aioxeQ8ZK+MbE9F26qVzu/CxBhxy1cOJT1r5T0OU596yYwj30Ok=,iv:YhqfktWPT34xT2WVmG+Sm4QAvOrRK3gQTBkqtJEGZhI=,tag:dYUszjph73DLaljtdWcKvg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
